#!/bin/bash
#
# Parakeet-rs Initialization Script
# Downloads required models and creates .env configuration
#
# Usage: ./init.sh
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "========================================"
echo "  Parakeet-rs Initialization"
echo "========================================"
echo ""

# Check for required tools
check_requirements() {
    local missing=()

    if ! command -v curl &> /dev/null && ! command -v wget &> /dev/null; then
        missing+=("curl or wget")
    fi

    if ! command -v docker &> /dev/null; then
        missing+=("docker")
    fi

    if [ ${#missing[@]} -ne 0 ]; then
        echo "Error: Missing required tools: ${missing[*]}"
        echo "Please install them and try again."
        exit 1
    fi
}

# Load HF_TOKEN from .env if exists
load_hf_token() {
    if [ -f ".env" ]; then
        HF_TOKEN=$(grep -E "^HF_TOKEN=" .env 2>/dev/null | cut -d'=' -f2 || echo "")
    fi
    # Also check environment variable
    HF_TOKEN="${HF_TOKEN:-$HUGGING_FACE_HUB_TOKEN}"
}

# Download file with progress (with optional HF auth)
download_file() {
    local url="$1"
    local output="$2"

    if [ -f "$output" ]; then
        echo "  [SKIP] $output already exists"
        return 0
    fi

    echo "  [DOWN] Downloading $output..."
    if command -v curl &> /dev/null; then
        if [ -n "$HF_TOKEN" ]; then
            curl -L --progress-bar -H "Authorization: Bearer $HF_TOKEN" "$url" -o "$output"
        else
            curl -L --progress-bar "$url" -o "$output"
        fi
    else
        if [ -n "$HF_TOKEN" ]; then
            wget --show-progress -q --header="Authorization: Bearer $HF_TOKEN" "$url" -O "$output"
        else
            wget --show-progress -q "$url" -O "$output"
        fi
    fi
    echo "  [DONE] $output"
}

# Download TDT model (multilingual transcription)
download_tdt_model() {
    echo ""
    echo "[1/2] Downloading TDT Model (Multilingual Transcription)..."
    echo "      Source: huggingface.co/istupakov/parakeet-tdt-0.6b-v3-onnx"
    echo ""

    mkdir -p tdt

    local base_url="https://huggingface.co/istupakov/parakeet-tdt-0.6b-v3-onnx/resolve/main"

    download_file "$base_url/encoder-model.onnx" "tdt/encoder-model.onnx"
    download_file "$base_url/encoder-model.onnx.data" "tdt/encoder-model.onnx.data"
    download_file "$base_url/decoder_joint-model.onnx" "tdt/decoder_joint-model.onnx"
    download_file "$base_url/vocab.txt" "tdt/vocab.txt"
}

# Download Diarization model (speaker identification)
download_diarization_model() {
    echo ""
    echo "[2/2] Downloading Diarization Model (Speaker Identification)..."
    echo "      Source: huggingface.co/altunenes/parakeet-rs"
    echo ""

    local url="https://huggingface.co/altunenes/parakeet-rs/resolve/main/diar_streaming_sortformer_4spk-v2.onnx"
    download_file "$url" "diar_streaming_sortformer_4spk-v2.onnx"
}

# Create .env file from template
create_env_file() {
    echo ""
    echo "[ENV] Creating .env configuration file..."

    if [ -f ".env" ]; then
        echo "  [SKIP] .env already exists"
        echo "  To recreate, delete .env and run init.sh again"
        return 0
    fi

    # Detect public IP (optional)
    local public_ip=""
    if command -v curl &> /dev/null; then
        public_ip=$(curl -s --max-time 5 ifconfig.me 2>/dev/null || echo "")
    fi

    cat > .env << 'EOF'
# Parakeet-rs WebRTC Transcriber Configuration
# Generated by init.sh

# =============================================================================
# Hugging Face Configuration
# =============================================================================

# Hugging Face token for downloading gated/private models
# Get your token at: https://huggingface.co/settings/tokens
HF_TOKEN=

# =============================================================================
# Server Configuration
# =============================================================================

# GPU Mode (set to false for CPU-only)
USE_GPU=true

# HTTP/WebSocket server ports
PORT=8080
GPU_PORT=8090

# Public IP address for WebRTC ICE candidates
# Required for external access. Auto-detected or set manually.
PUBLIC_IP=

# =============================================================================
# Transcription Mode
# =============================================================================

# Enable speedy mode for lower latency transcription (recommended)
SPEEDY_MODE=true

# =============================================================================
# Model Paths (used inside Docker container)
# =============================================================================

TDT_MODEL_PATH=/app/models/tdt
DIAR_MODEL_PATH=/app/models/diarization/model.onnx
FRONTEND_PATH=/app/frontend

# =============================================================================
# TURN Server Configuration (for NAT traversal)
# Optional but recommended for public access
# =============================================================================

# TURN server URL (examples):
#   turn:your-server.com:3478?transport=tcp
#   turn:your-server.com:3478?transport=udp
#   turns:your-server.com:443
TURN_SERVER=

# TURN authentication credentials
TURN_USERNAME=
TURN_PASSWORD=

# =============================================================================
# Performance Tuning
# =============================================================================

# ONNX Runtime thread configuration
INTRA_THREADS=2
INTER_THREADS=1

# =============================================================================
# Logging
# =============================================================================

# Log level: error, warn, info, debug, trace
RUST_LOG=info
EOF

    # Set detected public IP if available
    if [ -n "$public_ip" ]; then
        sed -i "s/^PUBLIC_IP=$/PUBLIC_IP=$public_ip/" .env
        echo "  [INFO] Detected public IP: $public_ip"
    fi

    echo "  [DONE] Created .env"
    echo ""
    echo "  IMPORTANT: Edit .env to configure:"
    echo "    - HF_TOKEN (required for gated models)"
    echo "    - PUBLIC_IP (required for external WebRTC access)"
    echo "    - TURN_SERVER (recommended for NAT traversal)"
}

# Main
main() {
    check_requirements
    load_hf_token

    if [ -n "$HF_TOKEN" ]; then
        echo "[AUTH] Using Hugging Face token for downloads"
    else
        echo "[AUTH] No HF_TOKEN found (set in .env or environment for gated models)"
    fi

    download_tdt_model
    download_diarization_model
    create_env_file

    echo ""
    echo "========================================"
    echo "  Initialization Complete!"
    echo "========================================"
    echo ""
    echo "Next steps:"
    echo "  1. Edit .env to configure your settings"
    echo "  2. Run: ./run.sh [cpu|gpu]"
    echo ""
    echo "Model sizes:"
    if [ -d "tdt" ]; then
        du -sh tdt/
    fi
    if [ -f "diar_streaming_sortformer_4spk-v2.onnx" ]; then
        du -sh diar_streaming_sortformer_4spk-v2.onnx
    fi
}

main "$@"
